default-resources:
  slurm_extra: "'--qos=15d'"
  mem_mb: 10000

set-resources:
  annotations:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  bamstats:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  bed:
    slurm_extra: "'--qos=3d'"
    mem_mb: 20000

  bedfile:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  bed_index:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  bw:
    slurm_extra: "'--qos=3d'"
    mem_mb: 10000

  collapse:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  collapse_tpm:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  cram:
    slurm_extra: "'--qos=3d'"
    mem_mb: 10000

  cramindex:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  crosscheck:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  cutadapt:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  cutadapt_single:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  cutadapt_paired:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  fastqc:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  fc:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  fingerprint:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  flagstat:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  gct:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  genome:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  get_fastq:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  genePredToBed:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  gtfToGenePred:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  gzip_unmapped_mate1:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  gzip_unmapped_mate2:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  indexbam:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  indexrmdup:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  junctions:
    slurm_extra: "'--qos=3d'"
    mem_mb: 20000

  junction_annotation:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  junction_saturation:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  md5sum:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  metrics:
    slurm_extra: "'--qos=3d'"
    mem_mb: 20000

  metrics_report:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  multiqc:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  picard:
    slurm_extra: "'--qos=3d'"
    mem_mb: 20000

  qc:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  refdata:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  report:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  samstats:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  sortbam_star:
    slurm_extra: "'--qos=3d'"
    mem_mb: 20000

  star:
    slurm_extra: "'--qos=3d'"
    mem_mb: 50000

  strandedness:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  tpm:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  validate_fastq:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000

  validate_gzip:
    slurm_extra: "'--qos=3h'"
    mem_mb: 10000
